### ISSUE TITLE
Please update

### ISSUE THREAD

**Issue by CBJamo** [clearpath-gbp/libswiftnav-release#1]
Would it be possible to get this updated? Libswiftnav is undergoing rapid development at the moment due to the imminent release of the Piksi GPS, and several large changes have occurred since the last update.

**Comment by mikepurvis** [comment]
Yes, absolutely. libswiftnav hasn't made a tagged release in a while. Do you have a sense what a suitable tag or point in time would be to make the release? I'd prefer not to just pick one at random.

**Comment by CBJamo** [comment]
I have no idea, but @fnoble could probably shed some light on the situation.

**Comment by fnoble** [comment]
Hi, we probably won't be tagging an official release until around April time when things have converged a bit closer to the Piksi release version.

What functionality are you guys using? If its just the coordinate systems code then I believe that hasn't changed much since last year. Happy to add a tag at some commit if that helps with your release process.

**Comment by mikepurvis** [comment]
@fnoble Having a tag is not essential. Would would actually be a help would be adding a package.xml file to the root of the repo, and `install()`ing it via CMake—currently [this one](https://github.com/clearpath-gbp/libswiftnav-release/blob/master/hydro/package.xml) gets patched in by the bloom packaging process.

If this is of interest, I can prepare a PR which makes the necessary changes to upstream, and then do another release into ROS Hydro.

**Comment by fnoble** [comment]
Happy to add that file, perhaps so it doesn't affect non ROS users though it could go in a subfolder called "external" or something and have it only installed by a specific target, e.g. make install_ros? 

Where does the file get installed to? Another option would be to get CMake to detect a ROS installation and only install the file if it is found. I don't really know anything about the ROS ecosystem so open to any suggestions.

What do you think?

**Comment by CBJamo** [comment]
> What functionality are you guys using? 

My interest is the sbp code for a piksi driver in ros. It would be nice for it to be in a nice ros-compatible (catkin) release.

The other thing that would make the process much nicer is either a cmakeconfig or a pkgconfig to allow us to build against the library without absolute path tomfoolery.

**Comment by mikepurvis** [comment]
It does need to be in the root directory, unfortunately—probably easiest to just keep patching it in during the packaging process. I need to patch anyway to disable the processor-specific optimizations. No worries on that score.

@CBJamo I see that the install locations have moved around, but at least with the previously released version, I was able to just find_library the shared object. Check it out [here](https://github.com/clearpathrobotics/enu/blob/hydro/CMakeLists.txt). Though I agree, having it be find_package-able would be the best.

**Comment by CBJamo** [comment]
Given the 0.8-stable branch/tag, can we get a release pushed through?

**Comment by mikepurvis** [comment]
Yes, sorry for the delay!

I've created a new Hydro release for the v0.8 tag. When it's built successfully, I'll release the same into Indigo. Track the status here: http://www.ros.org/debbuild/hydro.html?q=swiftnav

**Comment by mikepurvis** [comment]
Build failing because [libswiftnav asks for CMake 2.8.9](http://jenkins.ros.org/view/HbinP32/job/ros-hydro-swiftnav_binarydeb_precise_i386/15/console). Will retry.

**Comment by CBJamo** [comment]
Any word on the more recent updates, or an Indigo release?

**Comment by mikepurvis** [comment]
There was a request recently from @PaulBouchier as well. I can't promise any particular timeline, sorry.

**Comment by mikepurvis** [comment]
Okay, we should have a v0.13 release for Indigo in shadow by tomorrow: https://github.com/ros/rosdistro/pull/6329

Would appreciate some testing on that, @CBJamo and @PaulBouchier.

**Comment by PaulBouchier** [comment]
Fantastic! Thanks Mike. CBJamo doesn't have HW at present, but I do. I'll give it a whirl & let you know.

**Comment by PaulBouchier** [comment]
Oops - I missed the comment that this is for Indigo. I'm still on Hydro. Would you mind releasing for Hydro Mike? Meanwhile I'll manually extract the new library from the Indigo release & make sure it works in hydro with the new FW and the piksi driver.
Thanks
Paul

**Comment by mikepurvis** [comment]
Hmm. I'd rather not, in case it breaks the enu package. I guess I can try a manual build and see if there are any problems.

Either way, looks like the Indigo build is [having an issue anyway](http://jenkins.ros.org/job/ros-indigo-swiftnav_binarydeb_trusty_amd64/1/console):

```
tmp/buildd/ros-indigo-swiftnav-0.13.0-1trusty-20141123-0640/clapack-3.2.1-CMAKE/F2CLIBS/libf2c/backspac.c: In function 'f_back':
/tmp/buildd/ros-indigo-swiftnav-0.13.0-1trusty-20141123-0640/clapack-3.2.1-CMAKE/F2CLIBS/libf2c/backspac.c:47:8: error: ignoring return value of 'fread', declared with attribute warn_unused_result [-Werror=unused-result]
   fread((char *)&n,sizeof(uiolen),1,f);
        ^
/tmp/buildd/ros-indigo-swiftnav-0.13.0-1trusty-20141123-0640/clapack-3.2.1-CMAKE/F2CLIBS/libf2c/backspac.c: At top level:
cc1: error: unrecognized command line option "-Wno-self-assign" [-Werror]
cc1: error: unrecognized command line option "-Wno-unknown-warning-option" [-Werror]
cc1: all warnings being treated as errors
make[4]: *** [clapack-3.2.1-CMAKE/F2CLIBS/libf2c/CMakeFiles/f2c.dir/backspac.c.o] Error 1
make[4]: Leaving directory `/tmp/buildd/ros-indigo-swiftnav-0.13.0-1trusty-20141123-0640/obj-x86_64-linux-gnu'
make[3]: *** [clapack-3.2.1-CMAKE/F2CLIBS/libf2c/CMakeFiles/f2c.dir/all] Error 2
make[3]: Leaving directory `/tmp/buildd/ros-indigo-swiftnav-0.13.0-1trusty-20141123-0640/obj-x86_64-linux-gnu'
make[2]: *** [all] Error 2
make[2]: Leaving directory `/tmp/buildd/ros-indigo-swiftnav-0.13.0-1trusty-20141123-0640/obj-x86_64-linux-gnu'
dh_auto_build: make -j1 returned exit code 2
make[1]: *** [override_dh_auto_build] Error 2
make[1]: Leaving directory `/tmp/buildd/ros-indigo-swiftnav-0.13.0-1trusty-20141123-0640'
make: *** [build] Error 2
dpkg-buildpackage: error: debian/rules build gave error exit status 2
```

Anyone know what's going on here?

**Comment by PaulBouchier** [comment]
ok - no sweat. It's getting close to time I transitioned to indigo anyway. And I can test the 0.13 release in hydro with a manual build & make sure everything works. I'll let you know the results when I test with HW today.

**Comment by PaulBouchier** [comment]
One question: how do you make the release process work? You said what you release is the tag in swift navigations repo, and you don't have a clone of their repo, but what ends up in /opt/ros/hydro is just a couple of items: package.xml, the includes, & the libraries. What happened to all the other stuff that's in their repo? Does the build farm build the libraries? If so, where's the CMakeLists.txt? Do you have a little sandbox that you craft a ros release in?

**Comment by mikepurvis** [comment]
It's a bit black-magicky, but this is the general process: http://wiki.ros.org/bloom/Tutorials/ReleaseThirdParty

If you want to fiddle with it locally, you can do so like this:

```
mkdir workspace && cd workspace
git clone -b release/indigo/swiftnav https://github.com/clearpath-gbp/libswiftnav-release src/libswiftnav
catkin_make_isolated --install
source install_isolated/setup.bash
```

Now create a regular catkin workspace elsewhere, and it'll chain off this one— you should be able to find and link to libswiftnav exactly as if it's installed. If you want to re-chain an existing workspace off this one, just delete `build` and `devel` and rebuild it from scratch, and you should have the right chain. You can check it by printing out `CMAKE_PREFIX_PATH`.

@wjwwood can confirm that I'm not completely off my rocker here.

**Comment by mikepurvis** [comment]
If you're feeling spunky and want to try building the deb instead of using a workspace, you can try this:

```
git clone -b debian/ros-indigo-swiftnav_0.13.0-1_trusty https://github.com/clearpath-gbp/libswiftnav-release libswiftnav
cd libswiftnav
git-buildpackage -uc -us  --git-ignore-new --git-upstream-tree=tag
```

However, this isn't actually working for me at the moment. The [local prerelease instructions](http://wiki.ros.org/bloom/Tutorials/PrereleaseTest#Perform_the_pre-release_locally) need to be updated for Trusty.

**Comment by wjwwood** [comment]
Those instructions should work fine, he could also add his packages to that workspace, in `workspace/src`, but chaining is also a good thing to do in order to prevent checking that swiftnav is built every time you build the workspace.

As far as I know the deb building process you outlined should also work, maybe you can open an issue on bloom with more details on what isn't working?

**Comment by mikepurvis** [comment]
@PaulBouchier @CBJamo I think as of https://github.com/ros/rosdistro/pull/6555 I've finally got v0.13 building on the indigo farm.

Please grab the deb from shadow and confirm.

**Comment by PaulBouchier** [comment]
Hi Mike,

Thanks for releasing this. I'm sorry for the delay on testing - I needed to
upgrade a laptop to 14.04 & install indigo in order to test it. I've now
installed from shadow and tried to build the swiftnav_piksi driver.

I'm having trouble building, and not a CMake expert. Initially I had the
following in my CMakeLists.txt, and it would build with the 0.8 library
(and also with my replaced components):

#find_package(swiftnav REQUIRED)
find_library(SWIFTNAV swiftnav)
now it can't find the library:
CMake Error: The following variables are used in this project, but they are
set to NOTFOUND.
Please set them or make sure they are set and tested correctly in the CMake
files:
SWIFTNAV
    linked by target "piksi" in directory
/home/bouchier/catkin_ws/src/swiftnav_piksi
    linked by target "piksitest" in directory
/home/bouchier/catkin_ws/src/swiftnav_piksi

So I uncommented the find_package line, and now I get a different error:

CMake Error at swiftnav_piksi/CMakeLists.txt:10 (find_package):
  By not providing "Findswiftnav.cmake" in CMAKE_MODULE_PATH this project
has
  asked CMake to find a package configuration file provided by "swiftnav",
  but CMake did not find one.

  Could not find a package configuration file provided by "swiftnav" with
any
  of the following names:

```
swiftnavConfig.cmake
swiftnav-config.cmake
```

  Add the installation prefix of "swiftnav" to CMAKE_PREFIX_PATH or set
  "swiftnav_DIR" to a directory containing one of the above files.  If
  "swiftnav" provides a separate development package or SDK, be sure it has
  been installed.

That doesn't seem right either - it shouldn't be looking for
swiftnavConfig.cmake. This would build with the previous (hydro) library.

Do you have any suggestions for things to try?

Thanks

Paul

**Comment by mikepurvis** [comment]
Hey @PaulBouchier,

My [enu package](https://github.com/clearpathrobotics/enu/blob/hydro/CMakeLists.txt) builds fine against  0.13.0-3. Note that swiftnav is not a catkin package— it's a plain CMake package, so there are a couple things it doesn't get for free, such as a CMake find module. Since it doesn't provide a bespoke one, and I haven't bothered to patch one in, you don't get `find_package` support. This is why you have to use `find_library` instead of `find_package`.

Now, `find_library` will only work if you've sourced the workspace in which swiftnav is installed. Do you definitely have the latest (0.13.0-3) [from shadow](http://wiki.ros.org/ShadowRepository) installed to `/opt/ros/indigo` on your machine?

**Comment by PaulBouchier** [comment]
Thanks for the pointer Mike. I had some path problems related to upgrading
from hydro and the order of deleting build/devel & so forth. It's now
trying to build but getting a link error in libswiftnav where xerbla is not
found:
Linking CXX executable
/home/bouchier/catkin_ws/devel/lib/swiftnav_piksi/piksi_node
/opt/ros/indigo/lib/libswiftnav.so: undefined reference to `xerbla_'
collect2: error: ld returned 1 exit status

AFICT, xerbla was an old fortran math function, presumably ported to c. Is
there some other package that swiftnav is dependent on for this?

Regards

Paul

**Comment by PaulBouchier** [comment]
Hmm - xerbla_ is supposed to be part of libswiftnav, according to the api
reference.
Curiouser and curiouser.

**Comment by mikepurvis** [comment]
You may have to install lapack and then link its SO as well:

```
sudo apt-get install liblapack3
```

If this is the fix, feel free to submit a PR that adds that as a run-depend to swiftnav's package.xml.

Otherwise, I'm afraid you're on your own to figure it out.

**Comment by PaulBouchier** [comment]
Hi Mike,

Installing liblapack3 didn't fix it. I think something went wrong with your
build - I cloned libswiftnav from the Swift Navigation site, built it, &
ran nm & grep'ed for the missing symbol:

bouchier@phb-netbook:~/src/libswiftnav/build$ nm src/libswiftnav-static.a |
grep xer
bouchier@phb-netbook:~/src/libswiftnav/build$ nm src/libswiftnav.so | grep
xer000000000002cfd2 T cblas_xerbla
000000000002dae8 T LAPACKE_xerbla
000000000002d438 T xerbla_

For some reason it's defined in libswiftnav.so but not in
libswiftnav-static.a

Doing the same on the libraries installed from the ros swiftnav package:

bouchier@phb-netbook:~/catkin_ws$ nm /opt/ros/indigo/lib/libswiftnav.so |
grep xer
nm: /opt/ros/indigo/lib/libswiftnav.so: no symbols
bouchier@phb-netbook:~/catkin_ws$ nm
/opt/ros/indigo/lib/libswiftnav-static.a | grep xer
bouchier@phb-netbook:~/catkin_ws$

I guess you stripped the .so, so I can't find out if it's defined. (Not
sure how anything else would find out.)

Regards

Paul

**Comment by mikepurvis** [comment]
The build output is here: http://jenkins.ros.org/job/ros-indigo-swiftnav_binarydeb_saucy_amd64/25/consoleFull

Looks like liblapack.a gets built, but there's never an SO generated, and the static lib doesn't end up installed. As I say, I don't have much bandwidth to look at this, but I'm happy to merge fixes if you can figure out what's up.

**Comment by PaulBouchier** [comment]
As a reminder, here's the linker error:
Linking CXX executable
/home/bouchier/catkin_ws/devel/lib/swiftnav_piksi/piksi_node
/opt/ros/indigo/lib/libswiftnav.so: undefined reference to `xerbla_'
collect2: error: ld returned 1 exit status

In the trusty build log at
http://jenkins.ros.org/job/ros-indigo-swiftnav_binarydeb_trusty_amd64/25/consoleFull
I find the following references to xerbla_, and build steps for
libswiftnav.so:
....
compile xerbla

[ 95%] Building C object lapacke/CMakeFiles/lapacke.dir/utils/lapacke_xerbla.c.o
cd /tmp/buildd/ros-indigo-swiftnav-0.13.0-3trusty-20141216-1440/obj-x86_64-linux-gnu/lapacke
&& /usr/lib/ccache/x86_64-linux-gnu-gcc   -Wall -Wextra
-Wno-strict-prototypes -Wno-unknown-warning-option -std=gnu99 -g -O2
-fstack-protector --param=ssp-buffer-size=4 -Wformat
-Werror=format-security -D_FORTIFY_SOURCE=2  -fPIC
-I/tmp/buildd/ros-indigo-swiftnav-0.13.0-3trusty-20141216-1440/lapacke/include
   -o CMakeFiles/lapacke.dir/utils/lapacke_xerbla.c.o   -c
/tmp/buildd/ros-indigo-swiftnav-0.13.0-3trusty-20141216-1440/lapacke/utils/lapacke_xerbla.c
...
archive the .o's
/usr/bin/ar cr liblapacke.a
CMakeFiles/lapacke.dir/src/lapacke_dgelss.c.o
CMakeFiles/lapacke.dir/src/lapacke_dgelss_work.c.o
CMakeFiles/lapacke.dir/src/lapacke_dgelsy.c.o
CMakeFiles/lapacke.dir/src/lapacke_dgelsy_work.c.o
CMakeFiles/lapacke.dir/utils/lapacke_xerbla.c.o
CMakeFiles/lapacke.dir/utils/lapacke_dge_trans.c.o
CMakeFiles/lapacke.dir/utils/lapacke_d_nancheck.c.o
CMakeFiles/lapacke.dir/utils/lapacke_dge_nancheck.c.o
....

build the so
/usr/lib/ccache/x86_64-linux-gnu-gcc  -fPIC -Wall -Wextra
-Wno-strict-prototypes -Wno-unknown-warning-option -std=gnu99 -g -O2
-fstack-protector --param=ssp-buffer-size=4 -Wformat
-Werror=format-security -D_FORTIFY_SOURCE=2    -shared
-Wl,-soname,libswiftnav.so -o libswiftnav.so
CMakeFiles/swiftnav.dir/ephemeris.c.o
CMakeFiles/swiftnav.dir/nav_msg.c.o CMakeFiles/swiftnav.dir/pvt.c.o
CMakeFiles/swiftnav.dir/tropo.c.o CMakeFiles/swiftnav.dir/track.c.o
CMakeFiles/swiftnav.dir/correlate.c.o
CMakeFiles/swiftnav.dir/coord_system.c.o
CMakeFiles/swiftnav.dir/linear_algebra.c.o
CMakeFiles/swiftnav.dir/prns.c.o CMakeFiles/swiftnav.dir/almanac.c.o
CMakeFiles/swiftnav.dir/gpstime.c.o CMakeFiles/swiftnav.dir/edc.c.o
CMakeFiles/swiftnav.dir/rtcm3.c.o CMakeFiles/swiftnav.dir/bits.c.o
CMakeFiles/swiftnav.dir/sbp.c.o CMakeFiles/swiftnav.dir/lambda.c.o
CMakeFiles/swiftnav.dir/amb_kf.c.o
CMakeFiles/swiftnav.dir/stupid_filter.c.o
CMakeFiles/swiftnav.dir/sbp_utils.c.o
CMakeFiles/swiftnav.dir/single_diff.c.o
CMakeFiles/swiftnav.dir/memory_pool.c.o
CMakeFiles/swiftnav.dir/dgnss_management.c.o
CMakeFiles/swiftnav.dir/sats_management.c.o
CMakeFiles/swiftnav.dir/ambiguity_test.c.o ../CBLAS/src/libcblas.a
../lapacke/liblapacke.a ../clapack-3.2.1-CMAKE/SRC/liblapack.a
../clapack-3.2.1-CMAKE/BLAS/SRC/libblas.a -lm
../clapack-3.2.1-CMAKE/F2CLIBS/libf2c/libf2c.a

.....

strip symbols
strip --remove-section=.comment --remove-section=.note
--strip-unneeded
debian/ros-indigo-swiftnav/opt/ros/indigo/lib/libswiftnav.so
    strip --strip-debug
debian/ros-indigo-swiftnav/opt/ros/indigo/lib/libswiftnav-static.a

run dpkg-shlibdeps to check dependencies
dpkg-shlibdeps -Tdebian/ros-indigo-swiftnav.substvars
-l/tmp/buildd/ros-indigo-swiftnav-0.13.0-3trusty-20141216-1440/debian/ros-indigo-swiftnav//opt/ros/indigo/lib/
debian/ros-indigo-swiftnav/opt/ros/indigo/lib/libswiftnav.so
dpkg-shlibdeps: warning:
debian/ros-indigo-swiftnav/opt/ros/indigo/lib/libswiftnav.so contains
an unresolvable reference to symbol xerbla_: it's probably a plugin

Note that dpkg-shlibdeps picks up the error.

By running strings on libswiftnav.so I find that xerbla_ is actually in the
file. I suspect strip is removing its linkage information because it's not
needed for relocation processing, and somehow that's triggering the
undefined reference error, but that's just a guess. --strip-unneeded is
supposed to be safe for reclocatable libraries, but not for static
libraries - don't know why.

Is it possible to build it unstripped in Jenkins and see if that fixes the
problem? (obvously the version I built from source is unstripped, and it
does not suffer this error).

Thanks

Paul

**Comment by mikepurvis** [comment]
Sorry, Paul, I don't know enough about what's going on here or what's different about the buildfarm environment. Perhaps @dirk-thomas has some idea.

**Comment by dirk-thomas** [comment]
I don't have anything to contribute to this. The farm is basically only building the Debian package with the standard tools and their default configuration. I don't know what it does for static libraries in that case.

I guess your best bet is to reproduce the same build locally by building a Debian package and install it and look into how it differs from a "normal" from-source build.
